### ISSUE TITLE
error: { msg: "Could not parse JSON", err: ... }

### ISSUE THREAD

**Issue by drom** [Protryon/ui-treeview#1]
Thank you for the nice component. I am trying to use in my html:

``` html
<ui-treeview expanded>{a:42}</ui-treeview>
```

 it and I am getting the following error:

![snapshot12](https://cloud.githubusercontent.com/assets/511872/5947838/0dfd4096-a6f5-11e4-9cb3-48f00521cf32.png)

Do you have any idea what I am doing wrong?

**Comment by jsoverson** [comment]
JSON requires double quotes around key names. You can use the `.display()` method in order to pass a javascript object.

**Comment by drom** [comment]
I am getting the same error for empty construct like this:

``` html
<ui-treeview expanded></ui-treeview>
```

**Comment by drom** [comment]
I have tried `.display()` but it gives an additional error:

```
Uncaught TypeError: undefined is not a function
```

And does not change the view itself.

**Comment by drom** [comment]
On related topic. That what I get running your `ui-treeview/index.html` demo case.
![snapshot13](https://cloud.githubusercontent.com/assets/511872/5949475/e35dd248-a702-11e4-8000-93857bb9f907.png)

**Comment by jsoverson** [comment]
you'll need to do a bower install to get polymer, and I probably didn't account for the empty case since it was used in a demo with a default.

**Comment by drom** [comment]
I do have polymer installed in `bower_components/polymer/` but your demo looking for polymer inside `ui-treeview`.

**Comment by jsoverson** [comment]
It looks for it inside `components/` during development so as not to contaminate the parent dir and is then built and placed in the root where it looks for it as a sibling to the project.

**Comment by drom** [comment]
Sorry for dummy questions, but:
I have the following files:

```
work/components/polymer/polymer.html
work/components/ui-treeview/ui-treeview.html
work/demo/index.html
```

Inside `work/demo/index.html` I have the following `import` :

``` html
<link rel="import" href="../components/ui-treeview/ui-treeview.html">
<ui-treeview id="ast" expanded>{"a":{"b":"c"}}</ui-treeview>
```

![snapshot13](https://cloud.githubusercontent.com/assets/511872/5950320/3e6ba35e-a70d-11e4-98bf-98766e08b8ff.png)

I am fixing this by importing `polymer` before `ui-treeview`:

``` html
<link rel="import" href="../components/polymer/polymer.html">
<link rel="import" href="../components/ui-treeview/ui-treeview.html">
<ui-treeview id="ast" expanded>{"a":{"b":"c"}}</ui-treeview>
```

Should `ui-treeview` component itself `import` `polymer`?

Then I get good static tree:
![snapshot13](https://cloud.githubusercontent.com/assets/511872/5950432/ee47f2ae-a70e-11e4-8b2f-c4c6b4a8d2da.png)

Then I run the following code:

``` js
var ast = document.getElementById('ast');
ast.display({b: {c: 'd'}});
```

and getting this error:
![snapshot13](https://cloud.githubusercontent.com/assets/511872/5950523/241d9716-a710-11e4-8f44-656ec24e74dd.png)

Which is: `ast.display({b: {c: 'd'}});` line.
Any idea why?

**Comment by drom** [comment]
Please discard my second question. My mistake. I forgot to check `polymer-ready` event.
But first question still valid: Should component itself import polymer?

**Comment by jsoverson** [comment]
Yep, it should, good call. I opened #2 and #3 for both the issues found here.
